name: API Integration Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11" # Turunkan ke Python 3.11

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run API Server
        run: |
          nohup python app.py &  # Start Flask di background
          sleep 5  # Tunggu server siap

      - name: Run Tests
        run: |
          python test_api.py  # Jalankan test API
