name: API Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Make wait-for-it executable
        run: chmod +x scripts/wait-for-it.sh

      - name: Start Flask Server
        run: |
          nohup python app.py &
          scripts/wait-for-it.sh 127.0.0.1 5000 30

      - name: Run API Tests
        run: |
          python test_api.py
