name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U test_user -d test_db"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client libpq-dev gcc python3-dev

      - name: Install Python packages
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Flask Server with Health Check
        run: |
          nohup python app.py &
          for i in {1..20}; do
            if curl -s http://127.0.0.1:5000/health; then
              echo "Flask server is ready"
              break
            fi
            echo "Waiting for Flask server to start... ($i/20)"
            sleep 2
          done

      - name: Run Tests
        run: |
          pytest test_api.py
