jobs:
  test:
    runs-on: ubuntu-latest # Sesuaikan jika pakai Windows
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client libpq-dev gcc python3-dev

      - name: Install Dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install visualstudio2022buildtools -y --no-progress
          choco install visualstudio2022-workload-vctools -y --no-progress

      - name: Install Python packages
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          pytest test_api.py
