name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client libpq-dev gcc python3-dev

      - name: Install Python packages
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Flask Server
        run: |
          python app.py &
          sleep 10

      - name: Run Tests
        run: |
          pytest test_api.py
